baseURL = "http://portfolio.gibson431.com/"
languageCode = "en-us"
title = "Portfolio"
theme = "PaperMod"

[menu]
main = [
  { identifier = "home", name = "Home", url = "/", weight = 10 },
  { identifier = "experience", name = "Experience", url = "/experience", weight = 20 },
  { identifier = "projects", name = "Projects", url = "/projects", weight = 30 },
]

[params]
showToc = false
TocOpen = false
ShowBreadCrumbs = true
ShowCopyCodeButtons = true
hideMeta = false

env = "production"

socialIcons = [
  { name = "email", url = "mailto:timmaxgibson@gmail.com" },
  { name = "linkedin", url = "https://www.linkedin.com/in/timothy-gibson-79b046182/" },
  { name = "github", url = "https://github.com/Gibson431" },
]

[params.assets]
favicon = "/assets/favicon.ico"

[params.profileMode]
enabled = true
title = "Tim Gibson"
subtitle = "Mechanical and Mechatronic Engineer"
buttons = [
  { name = "Resume", url = "https://docs.google.com/document/d/10i1PbkDcsTfmgpOHmHgqI20FMIqrVqjj/edit?usp=sharing&ouid=114057340355433321552&rtpof=true&sd=true" },
  { name = "This Page", url = "https://github.com/Gibson431/gibson431.github.io" },
]
imageUrl = "/home/profile.jpeg"
imageWidth = 220
imageHeight = 220
